### ISSUE TITLE
FIX: Books downloaded and opened with Zotero are not marked as Reading until book is closed

### ISSUE THREAD

**Issue by mergen3107** [stelzch/zotero.koplugin#12]
Hi @stelzch 

Recently, we fixed an issue in the plugin that was not marking newly downloaded articles as `Reading`.
This resulted into newly downloaded and opened not being shown in the History - `Reading` section.
It required to exit the book - by going to FM, switching to another book, or closing the KOReader - to be able to mark it.
This prevented me from quickly skimming through multiple articles back-and-forth.

The problem is solved in this line:
https://github.com/stelzch/zotero.koplugin/blob/43f7e1e2498b321a2282e4f19ec44165c8fe2580/main.lua#L105
By replacing it to:
```
                ReaderUI:showReader(BaseUtil.realpath(full_path))
```
See linked comment with the fix and associated ticket in KOReader's GitHub.
https://github.com/koreader/koreader/issues/11444#issuecomment-1982551502

Thank you!

**Comment by hius07** [comment]
I am going to fix this at the KOReader side, so don't worry.

**Comment by mergen3107** [comment]
Thank you @hius07 !

**Comment by hius07** [comment]
Not related. Is the duplication on purpose?
https://github.com/stelzch/zotero.koplugin/blob/43f7e1e2498b321a2282e4f19ec44165c8fe2580/main.lua#L200-L211

**Comment by mergen3107** [comment]
@hius07 
Sorry, I lost track. Were the changes you mentioned already done? In that case I can close this ticket. 

@stelzch 
Can you please address the question about duplication from hius07?

Thanks guys!

**Comment by mergen3107** [comment]
@hius07 
Sorry, I remembered. Yes, this issue was solved. Waiting for comments from @stelzch

**Comment by stelzch** [comment]
@hius07 
The duplication was not intentional, it must have crept in during a merge. Patch is in the pipeline. Thanks :)

Also thanks @mergen3107 for addressing the issue in KOReader.

If there are no objections I'll close the issue.

**Comment by mergen3107** [comment]
@stelzch 
Yes, thank you!
