### ISSUE TITLE
Browse database crash

### ISSUE THREAD

**Issue by hlinander** [stelzch/zotero.koplugin#2]
Tried installing [be93233](https://github.com/stelzch/zotero.koplugin/commit/be93233e0489c5cf9e208e6d07233ad4a65b07c3) on my Kobo Libra 2 with KoReader 2023.01. After copying over my full Zotero directory and setting the Zotero path in KoReader (worked fine) the plugin crashes at

`main.lua:366 attempt to call method 'init' (a nil value)`

**Comment by stelzch** [comment]
Thanks for the report. I was able to reproduce the issue, it seems related to changes in the `FrameContainer`.It should be fixed in commit 8f4858c460e340d48a8e09d31a15da93d75193d2.
Please verify the fix works, then I can close this issue :)

**Comment by hlinander** [comment]
Thank you!
8f4858c460e340d48a8e09d31a15da93d75193d2 works great here.
