### ISSUE TITLE
Bug: Dispatcher action doesn't work

### ISSUE THREAD

**Issue by mergen3107** [stelzch/zotero.koplugin#7]
Device: Kindle Scribe (5.16.2)
KOReader: v2023.10-55
Zotero: v0.2

Hi! Thank you very much for the Zotero plugin.

Dispatcher action for `Zotero` doesn't work - I assigned it to a gesture, but it does nothing when I trigger it. The same story when I put it in Quick Menu.

Thanks!

**Comment by stelzch** [comment]
Hi @mergen3107,
thanks for taking the time to report the issues.
Could you please check whether the above commit fixes the action works for you?

**Comment by mergen3107** [comment]
@stelzch 
Thank you! I confirm that it works! Both from FM and Reader.

I had to patch by hand because I applied the fix for BaseUtil and removed duplicate in Browse:
https://github.com/stelzch/zotero.koplugin/issues/12

**Comment by mergen3107** [comment]
[main.lua.txt](https://github.com/user-attachments/files/17235175/main.lua.txt)
Here is how my final `main.lua` looks like, so you can compare

**Comment by stelzch** [comment]
Great to hear that it is working!

**Comment by mergen3107** [comment]
@stelzch 

I tested it further and have more feedback :) 

Now that it is really quick to open "Browse" section of Zotero, it would be nice to be also able to sync Zotero from Quick menu (with a new dispatcher item). 

Or, in order not to break the sequence (maybe sync will be slower than opening Browse), is it possible to add a button inside Browse to sync?

**Comment by mergen3107** [comment]
For now I need to sync it via top menu first, then open Browse via Quick Menu - if I want to see the freshest articles from my Zotero
