### ISSUE TITLE
Zotero settings

### ISSUE THREAD

**Issue by mergen3107** [stelzch/zotero.koplugin#9]
Hi!
I can see Zotero tries to open settings upon init:
https://github.com/stelzch/zotero.koplugin/blob/43f7e1e2498b321a2282e4f19ec44165c8fe2580/main.lua#L138-L146
But it doesn't save that file yet? I don't see it in the koreader/settings.

Thanks!

**Comment by stelzch** [comment]
The settings are read and stored in `zoteroapi.lua`. They should end up in a file called `zotero/meta.lua` inside the koreader directory.
I've removed this legacy snippet of code above in a recent commit, again thanks for pointing it out.

I'll close the issue for now, if you still have questions feel free to reopen it :)
